name: Create PDF File

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Create a folder called output
        run: |
          mkdir output
          cp readme-stylesheet.css output/readme-stylesheet.css
          cp README.md output/${{ github.actor }}-README.md

      - name: Install pandoc and wkhtmltopdf
        run: |
          wget https://github.com/jgm/pandoc/releases/download/3.0.1/pandoc-3.0.1-1-amd64.deb
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb
          sudo apt install ./pandoc-3.0.1-1-amd64.deb
          sudo apt install ./wkhtmltox_0.12.6.1-2.jammy_amd64.deb

      - name: Convert MD to HTML
        run: |
          pandoc README.md -f markdown -t html -M title:Resume -c readme-stylesheet.css -s -o output/${{github.actor}}-readme.html

      - name: Convert HTML to PDF
        run: |
          wkhtmltopdf --enable-local-file-access output/${{github.actor}}-readme.html output/${{github.actor}}-readme.pdf

      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.actor }}'s Resume
          path: output

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./output/${{github.actor}}-readme.pdf
          asset_name: ${{github.actor}}-readme.pdf
          asset_content_type: application/pdf
